### ISSUE TITLE
When viewing pallets for an item, need a total of all cases.

### ISSUE THREAD

**Issue by shourovb** [Pongolabs/qlickboard-qip-1#37]
When viewing pallets for an item, need a total of all cases for that item i.e. a sum over all pallets.

**Comment by yuhe0925** [comment]
Sum of the pallets, and the total number of good, held and refused case now displways on the top of pallet inspection.

The total case number also displays on item view.

**Comment by yuhe0925** [comment]
Fixed the bug when the total number of case displayed as "Nah"
Some of the record data has empty value rather then null

**Comment by yuhe0925** [comment]
Fixed
